import { Box, Link, Text } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import { useContext, useEffect, useState } from 'react';
import { handleLogin, initializeOpenlogin } from '../util/web3auth';
import { AuthContext } from '../contexts/AuthContext';

const Home: NextPage = () => {
  const [loading, setLoading] = useState(false as boolean);
  const [openlogin, setSdk] = useState(undefined  as object|undefined);
  const { currentUser, setCurrentUser } = useContext(AuthContext);
  const [level, setChainLevel] = useState("l2"); // "l1" or "l2"

  useEffect(() => {
    setLoading(true);
    initializeOpenlogin(level, setCurrentUser, setSdk, setLoading);
  }, [level])

  return (
    <div>
      <Head>
        <title>Collective Action</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {
      loading ?
        <div>
            <div style={{ display: "flex", flexDirection: "column", width: "100%", justifyContent: "center", alignItems: "center", margin: 20 }}>
                <h1>....loading</h1>
            </div>
        </div> : <div>
        {
          (openlogin && (openlogin as any).privKey) ?
          <div>
            <span>Connected to : { level === "l1" ? "Goerli Network":  "Mumbai Matic testnet"} </span> 
          </div>:
            <div className="loginContainer">
                <h1 style={{ textAlign: "center" }}>Openlogin x Polygon</h1>
                <div onClick={()=>handleLogin(openlogin as object, setLoading, level, setCurrentUser)} className="btn">
                  Login
                </div>
            </div>
        }
        </div>
      }
    </div>
  )
}

export default Home
